[package]
name = "subseqfastq"
version = "0.1.0"
edition = "2021"

[dependencies]
flate2 = { version = "1.0.17", features = ["zlib-ng"], default-features = false }
tokio = { version = "1.18", features = ["fs", "io-util", "rt", "macros"] }
clap = "3.1.9"
rayon = "1.5"
